"""
Core configuration package
核心配置包
"""
from .bazi_analysis_config import (
    QIJI_FLOW_ANALYSIS_RULES,
    QIJI_FLOW_CORE_PROMPT,
    SHISHEN_DETAILED_CONFIG,
    HE_CHONG_CONFIG,
    SHENSHA_CONFIG,
    WUXING_STRENGTH_CRITERIA,
    ANALYSIS_OUTPUT_TEMPLATE,
    USAGE_GUIDE,
    ADVANCED_ANALYSIS_EXAMPLES
)

__all__ = [
    'QIJI_FLOW_ANALYSIS_RULES',
    'QIJI_FLOW_CORE_PROMPT',
    'SHISHEN_DETAILED_CONFIG',
    'HE_CHONG_CONFIG',
    'SHENSHA_CONFIG',
    'WUXING_STRENGTH_CRITERIA',
    'ANALYSIS_OUTPUT_TEMPLATE',
    'USAGE_GUIDE',
    'ADVANCED_ANALYSIS_EXAMPLES'
]
